### ISSUE TITLE
Confusing permission name

### ISSUE THREAD

**Issue by avoinea** [4teamwork/collective.deletepermission#12]
I think the new permission should be called `Delete object`.

As `Delete portal content` is so confusing and creates difficulties in understanding who should have this  permission and who should have `Delete objects` and where :)

In my opinion `Delete object` is more self-explanatory.

**Comment by buchi** [comment]
The permission name follows the same name pattern as used with CMF permission names. E.g. `Add portal content` and `Modify portal content`. Should be self-explanatory enough.

Further having two permissions with a name differing in only one character is a bad idea, as this could easly lead to specifying the wrong permission because of a typo.

We'll keep the permission name as is.
